version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{‌{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{‌{ checksum "package.json" }}

  deploy-to-heroku:
    docker:
      - image: cimg/node:16.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Deploy to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_PRODUCTION_APP}.git ${CIRCLE_BRANCH}:main -f
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_STAGING_APP}.git ${CIRCLE_BRANCH}:main -f
            else
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_DEV_APP}.git ${CIRCLE_BRANCH}:main -f
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-heroku:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - main
