version: 2.1
executors:
  first-step:
    run:
      name: The First Step
      command: |
        echo 'Hello World!'
        echo 'This is the delivery pipeline'

jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      executor: first-step