orbs:
  slack: circleci/slack@4.9.3
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{‌{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{‌{ checksum "package.json" }}

  deploy-to-heroku:
    docker:
      - image: cimg/node:16.16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Deploy to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_PRODUCTION_APP}.git ${CIRCLE_BRANCH}:main -f
            elif [ "${CIRCLE_BRANCH}" == "staging" ]
            then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_STAGING_APP}.git ${CIRCLE_BRANCH}:main -f
            else
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${HEROKU_DEV_APP}.git ${CIRCLE_BRANCH}:main -f
            fi



  notify-via-slack:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
  notify-via-slack-custom:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "Slack Notification"
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "$CIRCLE_BRANCH branch deployment to Heroku is complete. :thumbsup:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*:\n$CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When*:\ndate + '%m/%d/%Y %Y"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build*:\n$CIRCLE_BUILD_NUM"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Build*:\n$CIRCLE_PROJECT_USERNAME"
                    }
                  ]
                },
                {
                  "type": "Actions",
                  "elements": [
                    {
                      "type": "Button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
          event: always

#  deployment:
#    push_to_server:
#      branch: main
#      commands:
#        - rsync -avz _site/ u73769297@hamdelesalvele.com:/test
workflows:
#  build_and_deploy:
#    jobs:
#      - build
#      - deploy-to-heroku:
#          requires:
#            - build
#          filters:
#            branches:
#              only:
#                - develop
#                - staging
#                - main
#      - notify-via-slack:
#          requires:
#            - deploy-to-heroku
#          context:
#            - slack-secrets
#      - notify-via-slack-custom:
#          requires:
#            - deploy-to-heroku
#          context:
#            - slack-secrets

  test-build-and-deploy:
    jobs:
      - notify-via-slack-custom:
          context:
            - slack-secrets